# -*- coding: utf-8 -*-
"""birthday_reminder_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oILphW_bD1o0sQ4UyxARl6KUs8uM42_o
"""

import streamlit as st                     # For interactive GUI
import datetime                            # For date handling
import json                                # For saving birthdays to a file
import os                                  # To check if file exists

# File to store birthdays
FILE_PATH = "birthdays.json"

# Load existing birthdays or return default ones
def load_birthdays():
    if os.path.exists(FILE_PATH):
        with open(FILE_PATH, "r") as file:
            return json.load(file)
    else:
        return {
            "Sunday": "2012-03-15",
            "Victor": "1999-07-10",
            "Bob": "2004-12-25",
            "Aliyah": "2001-05-02",
            "John": "2022-03-15",
            "Esther": "2014-05-12"
        }

# Save updated birthday dictionary to file
def save_birthdays(birthdays):
    with open(FILE_PATH, "w") as file:
        json.dump(birthdays, file)

# Add "st", "nd", "rd", or "th" to the day number
def day_suffix(day):
    if 11 <= day <= 13:
        return 'th'
    last_digit = day % 10
    if last_digit == 1:
        return 'st'
    elif last_digit == 2:
        return 'nd'
    elif last_digit == 3:
        return 'rd'
    else:
        return 'th'

# Start of Streamlit UI
st.set_page_config(page_title="🎂 Birthday Reminder App", layout="centered")
st.title("🎉 Birthday Reminder")

# Load birthdays from JSON file
birthdays = load_birthdays()

# Show today’s date
today = datetime.date.today()
today_month = today.month
today_day = today.day
st.write(f"📅 Today's date is: **{today.strftime('%A, %B %d, %Y')}**")

# Section: Show reminders for today or upcoming this month
st.subheader("🎈 Today's and Upcoming Birthdays")

for name, date_str in birthdays.items():
    birthday_date = datetime.datetime.strptime(date_str, "%Y-%m-%d").date()

    if birthday_date.month == today_month and birthday_date.day == today_day:
        st.success(f"🎉 Reminder: **{name}**'s birthday is today!")
    elif birthday_date.month == today_month:
        suffix = day_suffix(birthday_date.day)
        formatted = birthday_date.strftime(f"%B {birthday_date.day}{suffix}")
        st.info(f"📌 Upcoming: **{name}**'s birthday is on {formatted}")

# Section: Form to add new birthday
st.subheader("➕ Add a New Birthday")

with st.form("add_birthday_form"):
    new_name = st.text_input("Enter the name:")
    new_date = st.date_input("Enter birthday date (YYYY-MM-DD)")
    submit = st.form_submit_button("Add Birthday")

    if submit:
        if new_name.strip():
            birthdays[new_name.strip()] = new_date.strftime("%Y-%m-%d")
            save_birthdays(birthdays)
            st.success(f"✅ {new_name}'s birthday has been added!")
        else:
            st.warning("⚠️ Please enter a valid name.")

# Optional: View all stored birthdays
with st.expander("📂 View All Birthdays"):
    for name, date in birthdays.items():
        st.write(f"🎁 {name} — {date}")