# -*- coding: utf-8 -*-
"""countdown_timer_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oILphW_bD1o0sQ4UyxARl6KUs8uM42_o
"""

import streamlit as st
import time

# Title of the app
st.title("⏱ Countdown Timer")

# User input
minutes = st.number_input("Minutes:", min_value=0, value=0)
seconds = st.number_input("Seconds:", min_value=0, max_value=59, value=30)
total_seconds = int(minutes * 60 + seconds)

# Countdown logic with Start button
if st.button("Start Countdown"):
    placeholder = st.empty()
    progress = st.progress(0)
    for i in range(total_seconds, 0, -1):
        mins, secs = divmod(i, 60)
        placeholder.markdown(f"## Time Left: {mins:02d}:{secs:02d}")
        progress.progress((total_seconds - i) / total_seconds)
        time.sleep(1)
    placeholder.markdown("## ⏰ Time's Up!")
    st.balloons()