# -*- coding: utf-8 -*-
"""currency_converter_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oILphW_bD1o0sQ4UyxARl6KUs8uM42_o
"""

import requests
import streamlit as st
import json
import os
from datetime import datetime

offline_rates = {
    "USD": {"EUR": 0.85, "NGN": 150, "GBP": 0.75},
    "EUR": {"USD": 1.17, "NGN": 176, "GBP": 0.88}
}

CACHE_FILE = "exchange_cache.json"
HISTORY_FILE = "conversion_history.json"

# Function to fetch exchange rates based on base currency
def get_exchange_rates(base_currency):
    try:
        if os.path.exists(CACHE_FILE):
            with open(CACHE_FILE, 'r') as file:
                cache = json.load(file)
                if base_currency in cache:
                    return cache[base_currency]

        url = f"https://api.exchangerate-api.com/v4/latest/{base_currency}"
        response = requests.get(url)
        data = response.json()

        cache = {}
        if os.path.exists(CACHE_FILE):
            with open(CACHE_FILE, 'r') as file:
                cache = json.load(file)
        cache[base_currency] = data['rates']
        with open(CACHE_FILE, 'w') as file:
            json.dump(cache, file)

        return data['rates']
    except:
        return offline_rates.get(base_currency, {})

# Function to save each conversion to history
def save_conversion_history(base, amount, results):
    history = []
    if os.path.exists(HISTORY_FILE):
        with open(HISTORY_FILE, 'r') as file:
            history = json.load(file)

    history.append({
        "timestamp": str(datetime.now()),
        "base_currency": base,
        "amount": amount,
        "results": results
    })

    with open(HISTORY_FILE, 'w') as file:
        json.dump(history, file, indent=2)

# UI using Streamlit
st.title("💱 Currency Converter (Offline, Multi-Conversion, History)")

base_currency = st.text_input("Enter base currency (e.g., USD, EUR):", "USD").upper()
target_currencies = st.text_input("Enter target currencies (comma-separated):", "EUR,NGN,GBP").upper().split(",")
amount = st.number_input("Enter amount:", min_value=0.0, format="%.2f")

if st.button("Convert"):
    rates = get_exchange_rates(base_currency)
    results = {}
    if rates:
        for target in target_currencies:
            target = target.strip()
            if target in rates:
                converted = amount * rates[target]
                results[target] = round(converted, 2)
                st.success(f"{amount} {base_currency} = {converted:.2f} {target}")
            else:
                st.warning(f"Invalid currency: {target}")
        if results:
            save_conversion_history(base_currency, amount, results)
    else:
        st.error("Could not fetch exchange rates.")

if st.checkbox("Show Conversion History"):
    if os.path.exists(HISTORY_FILE):
        with open(HISTORY_FILE, 'r') as file:
            history = json.load(file)
            for entry in reversed(history[-5:]):
                st.write(f"🕒 {entry['timestamp']}")
                st.write(f"{entry['amount']} {entry['base_currency']} → {entry['results']}")
                st.markdown("---")
    else:
        st.info("No history yet.")