# -*- coding: utf-8 -*-
"""email_slicer_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oILphW_bD1o0sQ4UyxARl6KUs8uM42_o
"""

import streamlit as st
import re

# Function to slice email
def email_slicer(email):
    email = email.lower()
    pattern = r'^[\w\.-]+@[\w\.-]+\.\w+$'
    if re.match(pattern, email):
        username, domain = email.split('@')
        return username, domain
    return None, None

# Function to categorize domain
def categorize_domain(domain):
    personal_domains = ['gmail.com', 'yahoo.com', 'outlook.com', 'hotmail.com']
    return 'Personal Email' if domain in personal_domains else 'Corporate/Other Email'

# Streamlit UI
st.title("📧 Email Slicer Tool")

email = st.text_input("Enter your email address:")

if email:
    username, domain = email_slicer(email)
    if username and domain:
        st.success("Valid email format!")
        st.write("### Email Breakdown:")
        st.write(f"- **Username**: `{username}`")
        st.write(f"- **Domain**: `{domain}`")
        st.write(f"- **Domain Type**: `{categorize_domain(domain)}`")
    else:
        st.error("❌ Invalid email format. Please enter a valid email like `user@example.com`.")