# -*- coding: utf-8 -*-
"""expense_tracker_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oILphW_bD1o0sQ4UyxARl6KUs8uM42_o
"""

import streamlit as st
import sqlite3
from datetime import datetime

# Connect to SQLite database
conn = sqlite3.connect("expenses.db", check_same_thread=False)
cursor = conn.cursor()

# Create expenses table if it doesn't exist
cursor.execute("""
CREATE TABLE IF NOT EXISTS expenses (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT,
    category TEXT,
    amount REAL,
    description TEXT
)
""")
conn.commit()

# Function to add expense
def add_expense(date, category, amount, description):
    cursor.execute(
        "INSERT INTO expenses (date, category, amount, description) VALUES (?, ?, ?, ?)",
        (date, category, amount, description)
    )
    conn.commit()

# Function to fetch expenses (optionally by date)
def get_expenses(start_date=None, end_date=None):
    if start_date and end_date:
        cursor.execute(
            "SELECT date, category, amount, description FROM expenses WHERE date BETWEEN ? AND ? ORDER BY date",
            (start_date, end_date)
        )
    else:
        cursor.execute("SELECT date, category, amount, description FROM expenses ORDER BY date")
    return cursor.fetchall()

# Function to summarize by category
def get_summary():
    cursor.execute("SELECT category, SUM(amount) FROM expenses GROUP BY category")
    return cursor.fetchall()

# Page layout
st.title("💰 Personal Expense Tracker")
st.markdown("Track your daily spending, filter by date, and view category-wise summaries.")

# Sidebar for adding new expense
st.sidebar.header("➕ Add New Expense")
with st.sidebar.form("expense_form"):
    date = st.date_input("Date", datetime.today())
    category = st.selectbox("Category", ["Food", "Transport", "Bills", "Groceries", "Entertainment", "Other"])
    amount = st.number_input("Amount (₦)", min_value=0.0, step=0.01, format="%.2f")
    description = st.text_input("Description")
    submitted = st.form_submit_button("Add Expense")

    if submitted:
        add_expense(date.strftime("%Y-%m-%d"), category, amount, description)
        st.success("✅ Expense added successfully!")

# Filter section
st.subheader("📅 View Expenses")
with st.expander("Filter by Date Range"):
    col1, col2 = st.columns(2)
    with col1:
        start_date = st.date_input("Start Date", value=datetime(2024, 1, 1))
    with col2:
        end_date = st.date_input("End Date", value=datetime.today())

    if st.button("Apply Filter"):
        data = get_expenses(start_date.strftime("%Y-%m-%d"), end_date.strftime("%Y-%m-%d"))
        st.write("### Filtered Expenses")
        st.table(data)
    else:
        data = get_expenses()
        st.write("### All Expenses")
        st.table(data)

# Show summary
st.subheader("📊 Total Spending by Category")
summary = get_summary()
if summary:
    for cat, total in summary:
        st.write(f"**{cat}**: ₦{total:,.2f}")
else:
    st.info("No expenses recorded yet.")

# Close DB connection
conn.close()